apiVersion: v1
kind: Pod
metadata:
  name: model4
  labels: 
    app: model4
spec:
  containers:
  - name: model4
    image: bernnardosbo/model
    volumeMounts:
      - name: persistent-storage
        mountPath: /app/data
    env:
      - name: DATASET_URL
        value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds2.csv"
    command: ["python"]
    args: ["/app/main.py", "$(DATASET_URL)"]

  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: mypvc
